### ISSUE TITLE
[QoL] Pre-existing List Mode Misc. (drag&drop-ness, and 'not own channel' command warning)

### ISSUE THREAD

**Issue by lloyddunamis** [ThioJoe/YT-Spammer-Purge#571] opened 2022-02-05 18:13 UTC
Involved option: `7. Remove comments using a pre-existing list or log file`

1. The `TIP` there said drag&drop works, but drag&drop puts the fullpath to the CLI; it seems the program couldn't read the logs when it's done that way. (WinExe 2.15.0-Beta2)
2. _(Very minor, I think)_ Identify & tell users that the to-be-`Deleted`/-`Hidden` spam is not under the account being used. (hence only `Report`ing would be available (#569). Atm, it warns the user with a generic message.

Screenshot for reference.
![image](https://user-images.githubusercontent.com/6012867/152652942-55fa9f32-57d8-4544-bb84-5814447c2ca2.png)

**Comment by ThioJoe** [comment] 2022-02-05 19:34
For your second point, yea I'll probably have to add a note that it only works if you have removal privileges' for the channel.

For the first point, it looks like the problem is that it doesn't like the quotation marks around the path. I'll have to add a thing to account for that. It should work for now if there's no quotes:
![image](https://user-images.githubusercontent.com/12518330/152656175-f782beae-0c66-4901-9fe0-66a43e6527d2.png)

**Comment by ThioJoe** [comment] 2022-02-05 23:46
This should be fixed with the latest release, 2.15.0-Beta3

**Closed by ThioJoe** 2022-02-05 23:46 UTC
Labels: bug
