### ISSUE TITLE
[Bug]: A Timeout Error when Idled Too Long? (Code Z-3)

### ISSUE THREAD

**Issue by lloyddunamis** [ThioJoe/YT-Spammer-Purge#567] opened 2022-02-05 14:11 UTC
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [X] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I made sure of myself which spams to ban, so I took too long before issuing another command. I may have timed out on Youtube's side for waiting so long or something.
Idle time was around......8mins or longer.

Might it be alright to prompt the user to "re-log" or something w/o exiting the program, to be able to resume from where you currently are?
Low-prio though, since the program involves only a few steps...oh, but _oof my daily quota_.

Similar "timeout" issues of the same error code _(if specified)_ found but had a different resolution.
- #343, similar timeout error log, but this one occurs _during scanning_. It could've been their internet too though.

### Release version

2.14.3, 2.15.0-Beta1

### Steps to reproduce

Wait for around 8mins _(exact time not tested)_ before entering _I think_ a YT-querying command.
Error should appear in a minute or so after command is issued.

Bug happened to me on the following instances:
1. Inputting YT video/channel to scan.
2. Issuing the `REPORT` command.
3. A minute should pass with nothing happening, then error appears.

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
[Error Log 1, issuing REPORT command. 2.15.0-Beta1]
================================================================================
 (Not Case Sensitive) Input: REPORT

 Finishing Log File...

ERROR! Cannot write to logs\Spam_Log_2022-02-04_20-49-28.rtf. Is it open? Try closing the file before continuing.

 Press Enter to Try Again...



Traceback (most recent call last):[0 / 595] (In Groups of 50)
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1573, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1550, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1502, in primaryInstance
  File "Scripts\operations.py", line 702, in delete_found_comments
  File "Scripts\operations.py", line 667, in setStatus
  File "googleapiclient\_helpers.py", line 131, in positional_wrapper
  File "googleapiclient\http.py", line 922, in execute
  File "googleapiclient\http.py", line 221, in _retry_request
  File "googleapiclient\http.py", line 190, in _retry_request
  File "google_auth_httplib2.py", line 218, in request
  File "httplib2\__init__.py", line 1725, in request
  File "httplib2\__init__.py", line 1441, in _request
  File "httplib2\__init__.py", line 1393, in _conn_request
  File "http\client.py", line 1368, in getresponse
  File "http\client.py", line 317, in begin
  File "http\client.py", line 278, in _read_status
  File "socket.py", line 705, in readinto
  File "ssl.py", line 1273, in recv_into
  File "ssl.py", line 1129, in read
TimeoutError: The read operation timed out
------------------------------------------------
Error Message: The read operation timed out

Unknown Error - Code: Z-3 occurred. If this keeps happening, consider posting a bug report
on the GitHub issues page, and include the above error info.
================================================================================



[Error Log 2, Entering a video/channel. 2.15.0-Beta1]
================================================================================
Choice (1-9): 2

Enter a channel ID or Link to scan recent videos from
   > If scanning your own channel, just hit Enter

Enter Here: https://www.youtube.com/channel/UCOH3QdgesKmo5JXup5jBpnw
Traceback (most recent call last):
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1573, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1550, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 591, in primaryInstance
  File "Scripts\validation.py", line 158, in validate_channel_id
  File "googleapiclient\_helpers.py", line 131, in positional_wrapper
  File "googleapiclient\http.py", line 922, in execute
  File "googleapiclient\http.py", line 221, in _retry_request
  File "googleapiclient\http.py", line 190, in _retry_request
  File "google_auth_httplib2.py", line 218, in request
  File "httplib2\__init__.py", line 1725, in request
  File "httplib2\__init__.py", line 1441, in _request
  File "httplib2\__init__.py", line 1393, in _conn_request
  File "http\client.py", line 1368, in getresponse
  File "http\client.py", line 317, in begin
  File "http\client.py", line 278, in _read_status
  File "socket.py", line 705, in readinto
  File "ssl.py", line 1273, in recv_into
  File "ssl.py", line 1129, in read
TimeoutError: The read operation timed out
------------------------------------------------
Error Message: The read operation timed out

Unknown Error - Code: Z-3 occurred. If this keeps happening, consider posting a bug report
on the GitHub issues page, and include the above error info.
================================================================================

```

### Screenshots

![image](https://user-images.githubusercontent.com/6012867/152645153-2b21eb84-1ed6-4ab3-b7e5-763c7a5bcbcc.png)

**Comment by lloyddunamis** [comment] 2022-02-05 14:54
Oh. I was unsure earlier and mistook the edited out log for Beta2, but here's the error for **2.15.0-Beta2**. Idled for around 9m30s.
```shell
                          --- Scanning ---

Traceback (most recent call last):
  File "Scripts\operations.py", line 41, in get_comments
  File "googleapiclient\_helpers.py", line 131, in positional_wrapper
  File "googleapiclient\http.py", line 922, in execute
  File "googleapiclient\http.py", line 221, in _retry_request
  File "googleapiclient\http.py", line 190, in _retry_request
  File "google_auth_httplib2.py", line 218, in request
  File "httplib2\__init__.py", line 1725, in request
  File "httplib2\__init__.py", line 1441, in _request
  File "httplib2\__init__.py", line 1393, in _conn_request
  File "http\client.py", line 1368, in getresponse
  File "http\client.py", line 317, in begin
  File "http\client.py", line 278, in _read_status
  File "socket.py", line 705, in readinto
  File "ssl.py", line 1273, in recv_into
  File "ssl.py", line 1129, in read
TimeoutError: The read operation timed out
------------------------------------------------
 ERROR!   Error Message: The read operation timed out
------------------------------------------------

[!] Fatal Error Occurred During Scan!  Read the important info below!```

**Screenshots**
![image](https://user-images.githubusercontent.com/6012867/152646833-2334c096-8715-4148-805c-c53e4547277a.png)

**Comment by lloyddunamis** [comment] 2022-02-05 15:05
Oh? This branch of decisions let me go back to the main menu, and now it's able to query to YT again. _(I wish I got a screenshot of it; will edit-amend it here if I get through it again)_

Though, it just encountered #558 in the end:
```shell
7.  [x13]  CATRIENS🦋           : Only for fans over 18 years old LOVEME.UNO/CORNELIA 🦋  mañas no se la  Megan: "...



Traceback (most recent call last):
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1591, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1568, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1202, in primaryInstance
  File "Scripts\logging.py", line 134, in print_comments
UnboundLocalError: local variable 'spamThreadSamplesContent' referenced before assignment
------------------------------------------------
Error Message: local variable 'spamThreadSamplesContent' referenced before assignment

Error - Code: X-2 occurred. This is almost definitely my fault and requires patching (big bruh moment)
```

**Comment by ThioJoe** [comment] 2022-02-05 17:03
Yea this was probably a one-off issue with the API connection or something. So I'll close it for now, because the other error is a dupe of 558

**Closed by ThioJoe** 2022-02-05 17:03 UTC
Labels: bug

**Comment by lloyddunamis** [comment] 2022-02-06 08:27
Oh. I shouldn't have referenced 558 since it's entirely a different issue; it just happened to encounter that error in the end of my instance in [2nd](#issuecomment-1030638601) & [3rd](#issuecomment-1030640819) comments.

I'm still getting that TimeoutError, after..._honestly I can't time all of them while trying to work with it but_ prolly exceeding the 8 minutes I mentioned.

This is for `2.15.0-Beta4` now.
![image](https://user-images.githubusercontent.com/6012867/152673061-6f2f49b9-0d13-4c44-99a0-7efeacb00f1d.png)
