### ISSUE TITLE
Filtering: Missing some spammers

### ISSUE THREAD

**Issue by Saladitas** [ThioJoe/YT-Spammer-Purge#409] opened 2022-01-22 22:21 UTC
### Filter Mode

String search

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

1.  [x7]   UCFRi7Mrj-Eg4QWDo4hklyNQ | Don't read profil...: Don't Read My Name                                                                 
2.  [x17]  UCabpWNparm9wcghtVcDu3Zg | Beast v2🔥           : Markipliers niece is burning in hellishflames because I make way better content... 
3.  [x18]  UC9-Z5bQ7pzeux5coBPfQbHg | KelvinBB            : MARKIPLIER IS GARBAGE!!!!!!!!! MY CONTENT IS WAY BETTER                            
4.  [x20]  UCGa_XM7JLH9Ecp9VSxEQpCA | YeaMan              : I'm better than mark I got heat on my paige.                                       
5.  [x2]   UCBtb0JoGQg3FrByYPIKYeGA | Kavetion            : MARKIPLIER IS DISGUSTING!  MY CONTENT IS WAY BETTER                                
6.  [x23]  UCxekbYecJn5HZ1eGbGdxSOA | 1 subb with notis...: Guys Markiplier is  my inspiration my parents said that if I get 2k likes on an...

### Video / Post Link

https://www.youtube.com/watch?v=lsT4eplt8NA

### (Optional) Additional Info / Context

There are more similar to this but I just didn't scan them all

**Comment by Firecul** [comment] 2022-01-23 00:03
It *is* catching them tbf but only from the duplicate detection.
![Screenshot_20220123_000206](https://user-images.githubusercontent.com/34950371/150659408-fe44d5d8-98f5-44a3-8bee-2f23f322f12b.png)

**Comment by ThioJoe** [comment] 2022-01-23 02:46
Yea these are becoming more common, I'll come up with some filters for them probably tomorrow

**Comment by ThioJoe** [comment] 2022-01-23 18:49
This is also basically a dupe of #395 so going to close this and continue on that other issue

**Closed by ThioJoe** 2022-01-23 18:49 UTC
Labels: filtering
