### ISSUE TITLE
Traceback when trying to view spam comments

### ISSUE THREAD

**Issue by WorldInCode** [ThioJoe/YT-Spammer-Purge#333] opened 2022-01-05 07:59 UTC
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

LogMode referenced before assignment apparently.

### Release version

2.7.0

### Steps to reproduce

https://user-images.githubusercontent.com/95570511/148181343-2aa390de-c92b-4910-9a08-55543800b158.mp4

### What platform are you seeing this problem on?

Windows

**Comment by KendallDoesCoding** [comment] 2022-01-05 10:26
Error lines 3452:

3562 I think was added recently? The line is within this component
try:
    main()
  except HttpError as e:
    traceback.print_exc()
    print("------------------------------------------------")
    print("Error Message: " + str(e))
    if e.status_code:
      print("Status Code: " + str(e.status_code))
      if e.error_details[0]["reason"]: # If error reason is available, print it
          reason = str(e.error_details[0]["reason"])
          print_exception_reason(reason)
      input("\nPress Enter to Exit...")
    else:
      print(f"{F.RED}Unknown Error - Code: X-2{S.R} occurred. If this keeps happening, consider posting a bug report on the GitHub issues page, and include the above error info.")
      input("\n Press Enter to Exit...")
  except SystemExit:
    sys.exit()
  else:
    print("\nFinished Executing.")      



Line 3346:
  # Prints list of spam comments
  if scanMode == "communityPost":
    scanVideoID = communityPostID
  print("\n\nAll Matched Comments: \n")
  print_comments(scanVideoID, list(matchedCommentsDict.keys()), loggingEnabled, scanMode, logMode)
  print(f"\n{F.WHITE}{B.RED} NOTE: {S.R} Check that all comments listed above are indeed spam.")
  print()

**Comment by ThioJoe** [comment] 2022-01-05 13:10
Hm are you using a config file? I have an idea of the cause

**Comment by WorldInCode** [comment] 2022-01-05 13:36
> Hm are you using a config file? I have an idea of the cause

Yeah... Something wrong with it again?

**Comment by FlyAway05** [comment] 2022-01-05 14:22
> Hm are you using a config file? I have an idea of the cause

Huh? I have the same problem but I didn't use config fresh download from github and fresh api .json

**Comment by miquelfire** [comment] 2022-01-05 14:27
I came to report the same thing as @heolet 

In my case, too lazy to make a config file.

**Comment by ThioJoe** [comment] 2022-01-05 14:36
Ok should be fixed in the latest release, 2.7.1: https://github.com/ThioJoe/YT-Spammer-Purge/releases/tag/v2.7.1

Not sure if @WorldInCode was mistaken about having a config file, because the issue appeared to have been when there was NO config file. But let me know if there is indeed an issue when there is a config file.

**Comment by ThioJoe** [comment] 2022-01-05 17:18
Actually turns out there was another bug, @WorldInCode was correct. The other crash was when the user chooses not to log make a log file when prompted.
Now fixed in 2.7.1

**Closed by ThioJoe** 2022-01-05 17:18 UTC
Labels: bug, in-progress
