### ISSUE TITLE
[Bug]: The new chanel names ar not working exampel: https://www.youtube.com/@Diagnosedan

### ISSUE THREAD

**Issue by hessel-a** [ThioJoe/YT-Spammer-Purge#977] opened 2022-11-19 17:25 UTC
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

example: 
https://www.youtube.com/@Diagnosedan
https://www.youtube.com/@CuriousMarc

error I get:
*****
Enter a channel ID or Link to scan recent videos from
   > If scanning your own channel, just hit Enter

Enter Here: https://www.youtube.com/@CuriousMarc

Error: Invalid Channel link or ID!
*****

### Release version

Latest

### Steps to reproduce

-------------------------------- Scanning Options --------------------------------
      1. Scan specific videos
      2. Scan recent videos for a channel
      3. Scan recent comments across your Entire Channel
      4. Scan a specific community post (Experimental)
      5. Scan recent community posts for a channel (Experimental)

--------------------------------- Other Options ----------------------------------
      6. Create your own config file(s) to run the program with pre-set settings
      7. Remove comments using a pre-existing list or log file
      8. Recover deleted comments using log file
      9. Check & Download Updates

Choice (1-9): 2

Enter a channel ID or Link to scan recent videos from
   > If scanning your own channel, just hit Enter

Enter Here: https://www.youtube.com/@CuriousMarc

Error: Invalid Channel link or ID!

Enter a channel ID or Link to scan recent videos from
   > If scanning your own channel, just hit Enter

Enter Here:

### What platform are you seeing this problem on?

Windows (.exe file)

### Screenshots

![image](https://user-images.githubusercontent.com/61541459/202863608-e520fad2-0bf3-495d-a65e-8b6fde8c6567.png)

**Comment by Lightning11wins** [comment] 2022-11-19 20:22
This is a duplicate of [another issue](https://github.com/ThioJoe/YT-Spammer-Purge/issues/974). The problem here is that that channel uses a URL with a handle that the program can't... handle yet (pun intended). Yes, I know where the door is.

**Comment by LunaticBFF57** [comment] 2022-12-04 08:11
Is this issue needed to be closed now since that this is a duplicate?

**Comment by ThioJoe** [comment] 2022-12-08 16:14
Closing this as duplicate of #974

**Closed by ThioJoe** 2022-12-08 16:14 UTC
Labels: Bug / Error
