### ISSUE TITLE
Add handles (suggestion)

### ISSUE THREAD

**Issue by domonkos11** [ThioJoe/YT-Spammer-Purge#984] opened 2022-12-04 15:44 UTC
Please allow the use of handles instead of channel links/IDs when scanning videos on a specific channel.

**Comment by Lightning11wins** [comment] 2022-12-05 19:23
This suggestion is a duplicate of issue #974, where the program rejects URLs with handles unless suggestions aren't able to be duplicates of issues.

**Comment by ThioJoe** [comment] 2022-12-12 16:53
Dupe of #974 also the latest beta should work with handles now

**Closed by ThioJoe** 2022-12-12 16:53 UTC
