### ISSUE TITLE
[Bug]: (Scanner found lots of spam and crashed.)

### ISSUE THREAD

**Issue by Okibdoki** [ThioJoe/YT-Spammer-Purge#796] opened 2022-04-11 19:04 UTC
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I found a video that looked like it had lots of spammy comments, so I put it in the scanner.  I was right, it had a lot of spam comments. The scanner crashed around 5,000 matches. The error message was "division by zero" and the error code was "Z-3".
I used simple-smart mode.

### Release version

2.16.8

### Steps to reproduce

1. Start YTSpammerPurge.2.16.8.exe
2. Select 1 and press enter for "Scan Specific Video"
3. Enter this video URL: [https://www.youtube.com/watch?v=YiRPt4vrSSw]
4. Press y and enter when it asks if the video list is correct
5. Select 1 and press enter for "Auto-Smart Mode"
6. Press enter to begin scanning
7. Wait. When I did it, it crashed at 13,956 comments scanned.

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
Traceback (most recent call last):ents Scanned: 13956 | Replies Scanned: 3159 | Matches Found So Far: 4843
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1674, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1651, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1208, in primaryInstance
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1191, in scan_video
  File "Scripts\operations.py", line 138, in get_comments
  File "Scripts\operations.py", line 282, in get_replies
  File "Scripts\operations.py", line 465, in check_spam_threads
ZeroDivisionError: division by zero
------------------------------------------------
Error Message: division by zero

Unknown Error - Code: Z-3 occurred. If this keeps happening, consider posting a bug report
on the GitHub issues page, and include the above error info.
Short Link: TJoe.io/bug-report
```

### Screenshots

![Z-3Error](https://user-images.githubusercontent.com/70982938/162810196-fde21cd3-3474-4fa0-8752-293e67ad2f7a.JPG)

**Comment by Firecul** [comment] 2022-04-11 19:57
Duplicated in v2.26.8 .py version
![WindowsTerminal_Windows_PowerShell (40)](https://user-images.githubusercontent.com/34950371/162819373-dad79c7d-d6eb-4872-b755-2244615a2840.png)

**Comment by ThioJoe** [comment] 2022-04-11 20:36
Seems to be because the comment says it has replies, but then when you go to view them they're actually gone, so it's tripping up the program.

**Comment by ThioJoe** [comment] 2022-04-11 20:58
Ok should be fixed with 566f4d72d34149df048b0a87c5a7f62cc400ef28
I'll release 2.16.9 with the fix after I make sure it works

**Closed by ThioJoe** 2022-04-11 20:58 UTC
Labels: Bug / Error

**Comment by Firecul** [comment] 2022-04-11 21:26
> I'll release 2.16.9 with the fix after I make sure it works

I know I'm late but confirmed, it's working 
![WindowsTerminal_Windows_PowerShell (41)](https://user-images.githubusercontent.com/34950371/162836159-340adb52-dd60-461a-877b-e66955d9336d.png)

**Comment by Okibdoki** [comment] 2022-04-12 01:34
Ok, thanks.
