### ISSUE TITLE
Filtering: "finally its here" 

### ISSUE THREAD

**Issue by Jakesta13** [ThioJoe/YT-Spammer-Purge#852] opened 2022-06-06 16:56 UTC
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![Screenshot_20220606-125402](https://user-images.githubusercontent.com/10874330/172208282-24d85585-5483-4712-9c02-d84251153baa.png)

### Video / Post Link

https://youtu.be/_m7I_fp7pxs

### (Optional) Additional Info / Context

I noticed the wording is slightly different than usual,
such as "Finally it's here (video link)", this one is "(video link) Finally its here"

**Comment by Firecul** [comment] 2022-06-07 00:39
> Yea it will need to be in a new version because I'll need to add extra logic, since filtering just "finally it's here" would probably have too many false positives from people mentioning it.
> 
> Also the workaround is creators just disable hyperlinks in their comments section which eliminates these comments completely, along with many other types of spam.

https://github.com/ThioJoe/YT-Spammer-Purge/issues/836#issuecomment-1142367480

**Comment by Jakesta13** [comment] 2022-06-20 16:07
> Having that Ⓥ "fake checkmark" could also be something to watch out for.

Hey good catch, I didn't even notice it in this case - Though I have seen many fake Checkmarks on spam accounts so that could be an absolute way to detect

**Comment by Firecul** [comment] 2022-09-06 00:35
As the links above should be caught in the main lists now (https://github.com/ThioJoe/YT-Spam-Lists) this issue can probably be closed, if you have more URLs to submit please do that in the other repo.

**Comment by JM-Lemmi** [comment] 2022-09-06 05:33
This may be closed because its a duplicate of #836, but just adding some specific youtube vidos to the filter list will not get rid of this type of spam. The links are always changing

**Comment by Firecul** [comment] 2022-09-06 21:37
You are not wrong unfortunately.

**Comment by ThioJoe** [comment] 2022-09-15 15:44
I've added this with the new filtering method, the beta should catch it

**Closed by ThioJoe** 2022-09-15 15:44 UTC
Labels: Filtering Suggestion
