### ISSUE TITLE
UnboundLocalError: local variable 'videoID' referenced before assignment

### ISSUE THREAD

**Issue by edgarillo1** [ThioJoe/YT-Spammer-Purge#452] opened 2022-02-01 22:28 UTC
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to scan the follow video list:
https://www.youtube.com/watch?v=-jFoJZl28YA, https://www.youtube.com/watch?v=N4E-3aAKj5o&t=320s, https://www.youtube.com/watch?v=P-7KmYMBGyQ&t=513s, https://www.youtube.com/watch?v=H3V3LG-cmjE, https://www.youtube.com/watch?v=_mGtqD-I3bY, https://www.youtube.com/watch?v=c3Tbuemcjac, https://www.youtube.com/watch?v=73HkGuxLEBU, https://www.youtube.com/watch?v=6iQyxcXXmac, https://www.youtube.com/watch?v=dah5Y1bYnkk, https://www.youtube.com/watch?v=laAWYSKGtWE&t=25s, https://www.youtube.com/watch?v=9spIXKwMHhM, https://www.youtube.com/watch?v=1zrbN42PpRw, https://www.youtube.com/watch?v=7R2fk0isbkE, https://www.youtube.com/watch?v=SMhbkiJP6wE, https://www.youtube.com/watch?v=TFo88da-Nws, https://www.youtube.com/watch?v=NFKYICUVJKE, https://www.youtube.com/watch?v=-MYzOXfNj_o, https://www.youtube.com/watch?v=OjTlCMq_8bU, https://www.youtube.com/watch?v=_mfaBATxcUc, https://www.youtube.com/watch?v=4xOYoT18uU4, https://www.youtube.com/watch?v=oiVs5DddIuA, https://www.youtube.com/watch?v=kWrVbCPU-Bg, https://www.youtube.com/watch?v=RrgtW_dyRjc, https://www.youtube.com/watch?v=REsHWNNJS0w, https://www.youtube.com/watch?v=ARLJnOl0CsE, https://www.youtube.com/watch?v=BwmbJJMp4NU, https://www.youtube.com/watch?v=sQZhi6pU6Tg, https://www.youtube.com/watch?v=vyR5Bkq6XcQ, https://www.youtube.com/watch?v=l29K-nIdi5w, https://www.youtube.com/watch?v=LkXvokCfUgE, https://www.youtube.com/watch?v=lO04OoL6meE, https://www.youtube.com/watch?v=x_xgpVtOuYE, https://www.youtube.com/watch?v=Ae5C99jGANg, https://www.youtube.com/watch?v=mog93LaZS4U, https://www.youtube.com/watch?v=goIycBCu_zE
 but then the program send this out:
Scanning 1/35: Vestido The Great / Catalina la grande / Visita Palacio de las vacas / vestido rosa DIY

Scanning 2/35: Pintando ropa a mano inspirada en una botella artesanal

Scanning 3/35: Haciendo un Vestido Navideño y galletas / Recreando un vestido de Carolina Herrera

Scanning 4/35: Haciendo un vestido esponjoso doble vista // tutorial vestido organza

Scanning 5/35: Cómo hacer una camita de perro // material de Avena a los 3 meses

Scanning 6/35: Cómo hacer el disfraz de Wanda Maximoff de Wandavision

Scanning 7/35: Transformando una camisa de hombre a un romper. (Trift flip)

Scanning 8/35: Patchwork Top con costuras DIY

Traceback (most recent call last):
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1478, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1455, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1105, in primaryInstance
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1072, in scan_video
  File "Scripts\operations.py", line 132, in get_comments
UnboundLocalError: local variable 'videoID' referenced before assignment
------------------------------------------------
Error Message: local variable 'videoID' referenced before assignment

Error - Code: X-2 occurred. This is almost definitely my fault and requires patching (big bruh moment)
Please post a bug report on the GitHub issues page, and include the above error info.
Short Link: TJoe.io/bug-report
    (In the mean time, try using a previous release of the program.)

 Press Enter to Exit...

### Release version

2.14.0

### Steps to reproduce

1. Choice (1-9): 1
2. https://www.youtube.com/watch?v=-jFoJZl28YA, https://www.youtube.com/watch?v=N4E-3aAKj5o&t=320s, https://www.youtube.com/watch?v=P-7KmYMBGyQ&t=513s, https://www.youtube.com/watch?v=H3V3LG-cmjE, https://www.youtube.com/watch?v=_mGtqD-I3bY, https://www.youtube.com/watch?v=c3Tbuemcjac, https://www.youtube.com/watch?v=73HkGuxLEBU, https://www.youtube.com/watch?v=6iQyxcXXmac, https://www.youtube.com/watch?v=dah5Y1bYnkk, https://www.youtube.com/watch?v=laAWYSKGtWE&t=25s, https://www.youtube.com/watch?v=9spIXKwMHhM, https://www.youtube.com/watch?v=1zrbN42PpRw, https://www.youtube.com/watch?v=7R2fk0isbkE, https://www.youtube.com/watch?v=SMhbkiJP6wE, https://www.youtube.com/watch?v=TFo88da-Nws, https://www.youtube.com/watch?v=NFKYICUVJKE, https://www.youtube.com/watch?v=-MYzOXfNj_o, https://www.youtube.com/watch?v=OjTlCMq_8bU, https://www.youtube.com/watch?v=_mfaBATxcUc, https://www.youtube.com/watch?v=4xOYoT18uU4, https://www.youtube.com/watch?v=oiVs5DddIuA, https://www.youtube.com/watch?v=kWrVbCPU-Bg, https://www.youtube.com/watch?v=RrgtW_dyRjc, https://www.youtube.com/watch?v=REsHWNNJS0w, https://www.youtube.com/watch?v=ARLJnOl0CsE, https://www.youtube.com/watch?v=BwmbJJMp4NU, https://www.youtube.com/watch?v=sQZhi6pU6Tg, https://www.youtube.com/watch?v=vyR5Bkq6XcQ, https://www.youtube.com/watch?v=l29K-nIdi5w, https://www.youtube.com/watch?v=LkXvokCfUgE, https://www.youtube.com/watch?v=lO04OoL6meE, https://www.youtube.com/watch?v=x_xgpVtOuYE, https://www.youtube.com/watch?v=Ae5C99jGANg, https://www.youtube.com/watch?v=mog93LaZS4U, https://www.youtube.com/watch?v=goIycBCu_zE
3. Is this video list correct? (y/n): y
4. Choice (1-7): 2

### What platform are you seeing this problem on?

Windows (.exe file)

### Screenshots

![image](https://user-images.githubusercontent.com/15239946/152062008-fbc471d2-8514-4c73-b426-39014b855d72.png)
![Capture](https://user-images.githubusercontent.com/15239946/152062093-fdc6ff8a-6949-4acd-81d1-6d69933f16fa.PNG)

**Comment by ThioJoe** [comment] 2022-02-01 23:11
It looks like it was somehow caused by the video having no comments. I thought I handled that condition already but guess not. I'll fix it soon.

**Comment by verti4cal** [comment] 2022-02-01 23:58
Got the master branch with the last comment, but still the same error on MacOS M1.

<img width="1249" alt="grafik" src="https://user-images.githubusercontent.com/6603121/152071296-c03397ff-657a-4307-88a6-0c42af499d93.png">

**Comment by ThioJoe** [comment] 2022-02-02 00:50
Ok should be fixed with release 2.14.2

**Closed by ThioJoe** 2022-02-02 00:50 UTC
Labels: bug, in-progress
