### ISSUE TITLE
[Bug]: update function is broken v2.16.10

### ISSUE THREAD

**Issue by BrandiBlitz** [ThioJoe/YT-Spammer-Purge#983] opened 2022-12-01 04:15 UTC
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [x] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to check for update on 2.16.10, but then it gave me an error about a script being broken. I suspect the recent changes to all browsers broke some of the script.

### Release version

2.16.10

### Steps to reproduce

1. launch yt-spammer-purge and login
2. attempt an update check
3. for me, the error states line 1674, 1651, 895, and 95 had issues.

### What platform are you seeing this problem on?

Windows (.py script)

### Relevant log output

```shell
File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1674, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1651, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 895, in primaryInstance
  File "Scripts\files.py", line 95, in check_lists_update
FileNotFoundError: [Errno 2] No such file or directory: 'SpamPurge_Resources\\Spam_Lists2022.11.28.zip
```

### Screenshots

 ![image](https://user-images.githubusercontent.com/101225938/204964089-561fd8f1-048a-424c-bb5c-7903ef01d5d0.png)

**Comment by ThioJoe** [comment] 2022-12-08 16:16
It looks like the download failed for some reason, though not sure why. Maybe try again later, or ensure you're in a directory with the right permissions?

**Comment by BrandiBlitz** [comment] 2022-12-09 05:07
the thing is that every other time it will say invalid token and I have to login over and over again until it finally recognizes it. both Firefox and Opera have no issue themselves though.

**Comment by ThioJoe** [comment] 2022-12-19 21:18
Oh I see what the problem is, just gotta figure out what caused it. There is a missing `\\` in between the "Spam_Lists" directory and the zip file name

**Comment by ThioJoe** [comment] 2022-12-19 22:35
The latest commit in the [beta channel](https://github.com/ThioJoe/YT-Spammer-Purge/tree/2.17-Beta) *might* fix the issue. I added some retry logic to the download function that tries an alternative method if the first one fails. 

If you're still having the issue, try replacing `files.py` with the latest version here and see if it helps: https://github.com/ThioJoe/YT-Spammer-Purge/blob/2.17-Beta/Scripts/files.py

**Comment by BrandiBlitz** [comment] 2023-01-30 20:51
> The [latest commit](https://github.com/ThioJoe/YT-Spammer-Purge/commit/f6c500803dcf818b0e78fd0a44df1b32c6e2b05f) in the [beta channel](https://github.com/ThioJoe/YT-Spammer-Purge/tree/2.17-Beta) _might_ fix the issue. I added some retry logic to the download function that tries an alternative method if the first one fails.
> 
> If you're still having the issue, try replacing `files.py` with the latest version here and see if it helps: https://github.com/ThioJoe/YT-Spammer-Purge/blob/2.17-Beta/Scripts/files.py

hello, sorry for the late reply. I'm not on my laptop often, but it has seemed to work. thank you so much

**Comment by BrandiBlitz** [comment] 2023-01-30 20:55
> The [latest commit](https://github.com/ThioJoe/YT-Spammer-Purge/commit/f6c500803dcf818b0e78fd0a44df1b32c6e2b05f) in the [beta channel](https://github.com/ThioJoe/YT-Spammer-Purge/tree/2.17-Beta) _might_ fix the issue. I added some retry logic to the download function that tries an alternative method if the first one fails.
> 
> If you're still having the issue, try replacing `files.py` with the latest version here and see if it helps: https://github.com/ThioJoe/YT-Spammer-Purge/blob/2.17-Beta/Scripts/files.py

this one did help. I used both methods.

**Comment by BrandiBlitz** [comment] 2023-02-02 00:40
@ThioJoe I have run into another issue in the beta and stable release 2.16.0 and 2.17.0 beta 6.

I have the token.pickle in the root folder of my YT spammer purge folder and whenever I launch the exe, it asks me to authenticate my gmail and it doesn't work, b/c I have to delete the token to authenticate my google account.

**Comment by BrandiBlitz** [comment] 2023-02-02 00:45
@ThioJoe Infixed the issue. It turns out that having mor than one version of YT spammer purge in my root YT Spammer purge folder causes some weird interference between the latest stable and beta releases.

**Comment by KendallDoesCoding** [comment] 2023-02-23 08:20
@BrandiBlitz @ThioJoe - Please close this issue!

**Closed** 2023-03-04 20:36 UTC
Labels: Bug / Error
