### ISSUE TITLE
Executable doesn't run: When cmd prompt opens, closes almost immediately

### ISSUE THREAD

**Issue by mikekaylor98** [ThioJoe/YT-Spammer-Purge#733] opened 2022-03-10 20:09 UTC
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

When clicking YTSpammerPurge.2.16.5.exe the command prompt opens, a bunch of text appears, and it closes in under a second.
Still occurs after going through steps to create client_secrets file.

### Release version

2.16.5

### Steps to reproduce

1. Run it
2. Watch it close immediately

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
See screenshot taken from freeze frame in recorded video
```

### Screenshots

<img width="605" alt="report" src="https://user-images.githubusercontent.com/42279419/157746203-a4e0a70a-3668-4ab4-8a49-3805b7bd2364.png">

**Comment by ThioJoe** [comment] 2022-03-10 20:16
Hm well I know the solution, but not the cause. This happened to me after switching to Windows 11 on a new computer. I fixed it by installing OpenSSL: https://slproweb.com/products/Win32OpenSSL.html ( Win64 OpenSSL v1.1.1m )

Though I'm suspicious this happened in the first release I've made from Windows 11, and maybe it's going to happen to others. I'm assuming this error doesn't occur when running previous versions?

Can you tell me what version of windows you're running?

**Comment by ThioJoe** [comment] 2022-03-10 20:44
Ok I figured out the issue and it should be fixed now with the new release 2.16.6

**Closed by ThioJoe** 2022-03-10 20:44 UTC
Labels: bug

**Comment by mikekaylor98** [comment] 2022-03-10 21:04
Sorry for not replying, but I'm glad it was solved!
