### ISSUE TITLE
[Bug]: Old user account formats non-functional.

### ISSUE THREAD

**Issue by digitalcontemplation** [ThioJoe/YT-Spammer-Purge#508] opened 2022-02-03 02:10 UTC
### Duplicate Issues

- [ ] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

When scanning recent videos for a channel not your own, old user accounts do not function when in the format of:

https://www.youtube.com/user/*channel-user-name-here*

Recent user accounts do function, they use this format:

https://www.youtube.com/c/*channel-user-name-here*

### Release version

2.14.3

### Steps to reproduce

1. After launching the program, select option 2 to scan a channels recent videos
2. Scan using a older channel with the format of: https://www.youtube.com/user/*channel-user-name-here*
3. It outputs an incorrect video list.

### What platform are you seeing this problem on?

Windows (.exe file)

**Comment by digitalcontemplation** [comment] 2022-02-03 02:28
This may be related to [Issue #455](https://github.com/ThioJoe/YT-Spammer-Purge/issues/455).  Unsure if it is isolated or not.

**Comment by ThioJoe** [comment] 2022-02-03 02:50
Yea this is a duplicate of that, it's the same reason. It _can_ get a channel with that format, but if the channel is small it can get wonky. Gonna close this because dupe

**Closed by ThioJoe** 2022-02-03 02:50 UTC
Labels: bug
