### ISSUE TITLE
Hi, tried using 2.15.0 beta2 and it returned to post the bug report here.

### ISSUE THREAD

**Issue by GoukiMaster** [ThioJoe/YT-Spammer-Purge#743] opened 2022-03-14 04:16 UTC
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [X] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Traceback (most recent call last):
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1591, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1568, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1202, in primaryInstance
  File "Scripts\logging.py", line 134, in print_comments
UnboundLocalError: local variable 'spamThreadSamplesContent' referenced before assignment
------------------------------------------------
Error Message: local variable 'spamThreadSamplesContent' referenced before assignment

Error - Code: X-2 occurred. This is almost definitely my fault and requires patching (big bruh moment)
Please post a bug report on the GitHub issues page, and include the above error info.
Short Link: TJoe.io/bug-report
    (In the mean time, try using a previous release of the program.)

### Release version

2.15.0 Beta2

### Steps to reproduce

1. I ran the beta on page https://www.youtube.com/watch?v=X8beey6p85w
2. 
3. 

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
----------- YouTube Spammer Purge Log File -----------

Automatic Search Mode: Smart Mode 

Number of Matched Comments Found: 4

Number of Spam Bot Threads Found: 0

Number of Non-Matched, but Duplicate Comments Found: 47

IDs of Matched & Duplicate Comments: 
[ Ugy0n_0cY6hYv4SFMmt4AaABAg, UgwG850bVys8tFlitG54AaABAg, Ugyr6WIO7Lx3Irlw49x4AaABAg, Ugw_0Ux17OAnZz3yA4l4AaABAg, UgwVu1-h-SbDNDg3IAd4AaABAg, UgznIz8LjgADeJnaUN14AaABAg, Ugwy-r6n6UEElCbGP0B4AaABAg, Ugw1igrBU_xBOwdzkMJ4AaABAg, UgyRA2BKTWMVdcoKFqR4AaABAg, UgxkOSFlFwAjYDAtAzh4AaABAg, UgzfIogHy5IBdxU0ZR14AaABAg, UgwQToGUJS4JVOrlsAF4AaABAg, Ugyl6w3xIZbEF4zenL14AaABAg, UgxC1jwGId21KqAFnhB4AaABAg, UgzEjdp40PD9JYIsbsJ4AaABAg, UgxzIyag_1M0d1QwHQt4AaABAg, UgzRfiAhXb2e1pPpY5J4AaABAg, UgyWtzRkaPNnm7eN-oh4AaABAg, UgxpZqMTgQkoZMlNLsB4AaABAg, Ugy7VEBGMPh5urpzYL14AaABAg, UgwJJNLN-rC5uAAKLT94AaABAg, Ugw_Cl4KAzwiJk0v_0t4AaABAg, UgwQkSG_C0h1Ugj1dHt4AaABAg, UgyXgveYobvYqa_kraJ4AaABAg, UgxVOaDOUgkjX8_rXj94AaABAg, UgyL-CN_7VCrV3Zg8X54AaABAg, UgzP28KXV2-kmNUUoOF4AaABAg, UgxrvKD1huU7OXir4Md4AaABAg, Ugx8jSEDslpc47W7K954AaABAg, Ugw8sqWIFcnISJUh5Cd4AaABAg, UgzZX-t9QndqJwVRZH94AaABAg, UgydPhozm-gSBZO4IYl4AaABAg, UgwhN4YzEQ7CuYC1vkB4AaABAg, Ugz9gInd946Uwrq1d4V4AaABAg, UgycCXnEfGvu3HCGkdx4AaABAg, Ugz7ChfE1VS7soDNE5V4AaABAg, Ugw0o6qmFLGz8v6Ta7x4AaABAg, UgwENNeZvoNDZzLuyJp4AaABAg, Ugz44hXVbNUWKYsBHVt4AaABAg, Ugxxaq2lzC_7GdFB6SN4AaABAg, Ugx78LBOpeXVRRwOSQ94AaABAg, UgyzzIcwUznfeJNyhaJ4AaABAg, Ugyo0O0ecegJimUf7914AaABAg, UgwvMxLqGq4BkfWhY4h4AaABAg, Ugx6LzehYTXLcNtVWy14AaABAg, Ugzc1z8O-kbuuXBh0c14AaABAg, UgzhltbPDVAqkoX31Jd4AaABAg, Ugw6W9FHKIb1y-v_KXl4AaABAg, Ugyx2XE7vreoAibPPtx4AaABAg, Ugzh1tlFhOnNlBzSEON4AaABAg, UgwL1vSJq_ozKBOQCux4AaABAg ] 


1. Rossy- 🔥𝐆𝐨 𝐓𝐨 𝐌𝐲 𝐂𝐡𝐚𝐧𝐧𝐞𝐥 [𝐋!𝐯𝐞]🔞:  AJ deffo hitting that, no doubt
---------------------------------------------------------------------------------------------
     > Reason: Filter Match
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=Ugy0n_0cY6hYv4SFMmt4AaABAg 
     > Author Channel ID: UCd9J3_suj-_Wz_u2sk_aFIQ
=============================================================================================


2. SUSSY- 🔥𝐆𝐨 𝐓𝐨 𝐌𝐲 𝐂𝐡𝐚𝐧𝐧𝐞𝐥 [𝐋!𝐯𝐞]🔞:  AJ deffo hitting that, no doubt
---------------------------------------------------------------------------------------------
     > Reason: Filter Match
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgwG850bVys8tFlitG54AaABAg 
     > Author Channel ID: UCFoYBfA3egjy32tR2X-qqrA
=============================================================================================


3. Sussa-𝐹**СК МЕ - СНЕ𝒞𝒦 𝑀𝒴 Р𝑅𝟢𝐹𝐼𝐿Е🔞:  Let’s go Shannon
---------------------------------------------------------------------------------------------
     > Reason: Filter Match
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=Ugyr6WIO7Lx3Irlw49x4AaABAg 
     > Author Channel ID: UCFgY_1mol9enO4WfGk8SDuQ
=============================================================================================


4. Zello-𝐹**СК МЕ - СНЕ𝒞𝒦 𝑀𝒴 Р𝑅𝟢𝐹𝐼𝐿Е🔞:  Let’s go Shannon
---------------------------------------------------------------------------------------------
     > Reason: Filter Match
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=Ugw_0Ux17OAnZz3yA4l4AaABAg 
     > Author Channel ID: UCNH40MAvdPZDG9JR7zBcXpA
=============================================================================================




============================================================================================
=========================== Non-Matched, But Duplicate Comments ===========================
============================================================================================ 

5. NaughtyDreamer ! Belle:  AJ deffo hitting that, no doubt
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgwVu1-h-SbDNDg3IAd4AaABAg 
     > Author Channel ID: UCFwyIS84rpCdpGjLXbixpzQ
=============================================================================================


6. NaughtyDreamer ! Belle:  Colors seem brighter when you're around.
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgznIz8LjgADeJnaUN14AaABAg 
     > Author Channel ID: UCFwyIS84rpCdpGjLXbixpzQ
=============================================================================================


7. NaughtyDreamer ! Belle:  You should be thanked more often. Thank you.
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=Ugwy-r6n6UEElCbGP0B4AaABAg 
     > Author Channel ID: UCFwyIS84rpCdpGjLXbixpzQ
=============================================================================================


8. NaughtyDreamer ! Belle:  AJ deffo hitting that, no doubt
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=Ugw1igrBU_xBOwdzkMJ4AaABAg 
     > Author Channel ID: UCFwyIS84rpCdpGjLXbixpzQ
=============================================================================================


9. NaughtyDreamer ! Belle:  You should be thanked more often. Thank you.
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgyRA2BKTWMVdcoKFqR4AaABAg 
     > Author Channel ID: UCFwyIS84rpCdpGjLXbixpzQ
=============================================================================================


10. NaughtyDreamer ! Belle:  Never heard of her. I hope she does okay.
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgxkOSFlFwAjYDAtAzh4AaABAg 
     > Author Channel ID: UCFwyIS84rpCdpGjLXbixpzQ
=============================================================================================


11. NaughtyDreamer ! Belle:  She too cute to be a boxer
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgzfIogHy5IBdxU0ZR14AaABAg 
     > Author Channel ID: UCFwyIS84rpCdpGjLXbixpzQ
=============================================================================================


12. NaughtyDreamer ! Belle:  Let’s go Shannon
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgwQToGUJS4JVOrlsAF4AaABAg 
     > Author Channel ID: UCFwyIS84rpCdpGjLXbixpzQ
=============================================================================================


13. NaughtyDreamer ! Belle:  Hanging out with you is always fun.
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=Ugyl6w3xIZbEF4zenL14AaABAg 
     > Author Channel ID: UCFwyIS84rpCdpGjLXbixpzQ
=============================================================================================


14. NaughtyDreamer ! Belle:  AJ deffo hitting that, no doubt
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgxC1jwGId21KqAFnhB4AaABAg 
     > Author Channel ID: UCFwyIS84rpCdpGjLXbixpzQ
=============================================================================================


15. NaughtyDreamer ! Belle:  You should be thanked more often. Thank you.
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgzEjdp40PD9JYIsbsJ4AaABAg 
     > Author Channel ID: UCFwyIS84rpCdpGjLXbixpzQ
=============================================================================================


16. NaughtyDreamer ! Belle:  Let’s go Shannon
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgxzIyag_1M0d1QwHQt4AaABAg 
     > Author Channel ID: UCFwyIS84rpCdpGjLXbixpzQ
=============================================================================================


17. NaughtyDreamer ! Belle:  Lets go champ
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgzRfiAhXb2e1pPpY5J4AaABAg 
     > Author Channel ID: UCFwyIS84rpCdpGjLXbixpzQ
=============================================================================================


18. NaughtyDreamer ! Belle:  You are brave.
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgyWtzRkaPNnm7eN-oh4AaABAg 
     > Author Channel ID: UCFwyIS84rpCdpGjLXbixpzQ
=============================================================================================


19. NaughtyDreamer ! Belle:  YUMMY!
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgxpZqMTgQkoZMlNLsB4AaABAg 
     > Author Channel ID: UCFwyIS84rpCdpGjLXbixpzQ
=============================================================================================


20. NaughtyDreamer ! Belle:  You are brave.
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=Ugy7VEBGMPh5urpzYL14AaABAg 
     > Author Channel ID: UCFwyIS84rpCdpGjLXbixpzQ
=============================================================================================


21. NaughtyDreamer ! Belle:  Lets go champ
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgwJJNLN-rC5uAAKLT94AaABAg 
     > Author Channel ID: UCFwyIS84rpCdpGjLXbixpzQ
=============================================================================================


22. NaughtyDreamer ! Belle:  She’s peeeeeeng
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=Ugw_Cl4KAzwiJk0v_0t4AaABAg 
     > Author Channel ID: UCFwyIS84rpCdpGjLXbixpzQ
=============================================================================================


23. NaughtyDreamer ! Belle:  Lets go champ
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgwQkSG_C0h1Ugj1dHt4AaABAg 
     > Author Channel ID: UCFwyIS84rpCdpGjLXbixpzQ
=============================================================================================


24. NaughtyDreamer ! Belle:  You are brave.
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgyXgveYobvYqa_kraJ4AaABAg 
     > Author Channel ID: UCFwyIS84rpCdpGjLXbixpzQ
=============================================================================================


25. NaughtyDreamer ! Belle:  AJ got himself a real one
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgxVOaDOUgkjX8_rXj94AaABAg 
     > Author Channel ID: UCFwyIS84rpCdpGjLXbixpzQ
=============================================================================================


26. NaughtyDreamer ! Belle:  Hanging out with you is always fun.
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgyL-CN_7VCrV3Zg8X54AaABAg 
     > Author Channel ID: UCFwyIS84rpCdpGjLXbixpzQ
=============================================================================================


27. NaughtyDreamer ! Belle:  AJ deffo hitting that, no doubt
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgzP28KXV2-kmNUUoOF4AaABAg 
     > Author Channel ID: UCFwyIS84rpCdpGjLXbixpzQ
=============================================================================================


28. NaughtyDreamer ! Belle:  AJ deffo hitting that, no doubt
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgxrvKD1huU7OXir4Md4AaABAg 
     > Author Channel ID: UCFwyIS84rpCdpGjLXbixpzQ
=============================================================================================


29. ~NaughtyCuteness💋Marilyn:  AJ got himself a real one
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=Ugx8jSEDslpc47W7K954AaABAg 
     > Author Channel ID: UCeJ9LsUx9xeIKC6ibIxtOSQ
=============================================================================================


30. ~NaughtyCuteness💋Marilyn:  Let’s go Shannon
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=Ugw8sqWIFcnISJUh5Cd4AaABAg 
     > Author Channel ID: UCeJ9LsUx9xeIKC6ibIxtOSQ
=============================================================================================


31. ~NaughtyCuteness💋Marilyn:  Let’s go Shannon
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgzZX-t9QndqJwVRZH94AaABAg 
     > Author Channel ID: UCeJ9LsUx9xeIKC6ibIxtOSQ
=============================================================================================


32. ~NaughtyCuteness💋Marilyn:  She’s smokin hot ain’t she…may even give Natasha jonas a run for her money lol
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgydPhozm-gSBZO4IYl4AaABAg 
     > Author Channel ID: UCeJ9LsUx9xeIKC6ibIxtOSQ
=============================================================================================


33. ~NaughtyCuteness💋Marilyn:  She’s peeeeeeng
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgwhN4YzEQ7CuYC1vkB4AaABAg 
     > Author Channel ID: UCeJ9LsUx9xeIKC6ibIxtOSQ
=============================================================================================


34. ~NaughtyCuteness💋Marilyn:  AJ got himself a real one
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=Ugz9gInd946Uwrq1d4V4AaABAg 
     > Author Channel ID: UCeJ9LsUx9xeIKC6ibIxtOSQ
=============================================================================================


35. ~NaughtyCuteness💋Marilyn:  She’s peeeeeeng
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgycCXnEfGvu3HCGkdx4AaABAg 
     > Author Channel ID: UCeJ9LsUx9xeIKC6ibIxtOSQ
=============================================================================================


36. ~NaughtyCuteness💋Marilyn:  Smh
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=Ugz7ChfE1VS7soDNE5V4AaABAg 
     > Author Channel ID: UCeJ9LsUx9xeIKC6ibIxtOSQ
=============================================================================================


37. ~NaughtyCuteness💋Marilyn:  AJ got himself a real one
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=Ugw0o6qmFLGz8v6Ta7x4AaABAg 
     > Author Channel ID: UCeJ9LsUx9xeIKC6ibIxtOSQ
=============================================================================================


38. ~NaughtyCuteness💋Marilyn:  AJ deffo hitting that, no doubt
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgwENNeZvoNDZzLuyJp4AaABAg 
     > Author Channel ID: UCeJ9LsUx9xeIKC6ibIxtOSQ
=============================================================================================


39. ~NaughtyCuteness💋Marilyn:  She’s peeeeeeng
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=Ugz44hXVbNUWKYsBHVt4AaABAg 
     > Author Channel ID: UCeJ9LsUx9xeIKC6ibIxtOSQ
=============================================================================================


40. ~NaughtyCuteness💋Marilyn:  She’s smokin hot ain’t she…may even give Natasha jonas a run for her money lol
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=Ugxxaq2lzC_7GdFB6SN4AaABAg 
     > Author Channel ID: UCeJ9LsUx9xeIKC6ibIxtOSQ
=============================================================================================


41. ~NaughtyCuteness💋Marilyn:  Cutie 🥧 👌🏽
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=Ugx78LBOpeXVRRwOSQ94AaABAg 
     > Author Channel ID: UCeJ9LsUx9xeIKC6ibIxtOSQ
=============================================================================================


42. ~NaughtyCuteness💋Marilyn:  YUMMY!
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgyzzIcwUznfeJNyhaJ4AaABAg 
     > Author Channel ID: UCeJ9LsUx9xeIKC6ibIxtOSQ
=============================================================================================


43. ~NaughtyCuteness💋Marilyn:  She too cute to be a boxer
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=Ugyo0O0ecegJimUf7914AaABAg 
     > Author Channel ID: UCeJ9LsUx9xeIKC6ibIxtOSQ
=============================================================================================


44. ~NaughtyCuteness💋Marilyn:  AJ deffo hitting that, no doubt
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgwvMxLqGq4BkfWhY4h4AaABAg 
     > Author Channel ID: UCeJ9LsUx9xeIKC6ibIxtOSQ
=============================================================================================


45. ~NaughtyCuteness💋Marilyn:  AJ deffo hitting that, no doubt
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=Ugx6LzehYTXLcNtVWy14AaABAg 
     > Author Channel ID: UCeJ9LsUx9xeIKC6ibIxtOSQ
=============================================================================================


46. ~NaughtyCuteness💋Marilyn:  Cutie 🥧 👌🏽
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=Ugzc1z8O-kbuuXBh0c14AaABAg 
     > Author Channel ID: UCeJ9LsUx9xeIKC6ibIxtOSQ
=============================================================================================


47. ~NaughtyCuteness💋Marilyn:  YUMMY!
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgzhltbPDVAqkoX31Jd4AaABAg 
     > Author Channel ID: UCeJ9LsUx9xeIKC6ibIxtOSQ
=============================================================================================


48. ~NaughtyCuteness💋Marilyn:  Let’s go Shannon
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=Ugw6W9FHKIb1y-v_KXl4AaABAg 
     > Author Channel ID: UCeJ9LsUx9xeIKC6ibIxtOSQ
=============================================================================================


49. ~NaughtyCuteness💋Marilyn:  Cutie 🥧 👌🏽
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=Ugyx2XE7vreoAibPPtx4AaABAg 
     > Author Channel ID: UCeJ9LsUx9xeIKC6ibIxtOSQ
=============================================================================================


50. ~NaughtyCuteness💋Marilyn:  YUMMY!
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=Ugzh1tlFhOnNlBzSEON4AaABAg 
     > Author Channel ID: UCeJ9LsUx9xeIKC6ibIxtOSQ
=============================================================================================


51. ~NaughtyCuteness💋Marilyn:  AJ deffo hitting that, no doubt
---------------------------------------------------------------------------------------------
     > Reason: Duplicate
     > Direct Link: https://www.youtube.com/watch?v=X8beey6p85w&lc=UgwL1vSJq_ozKBOQCux4AaABAg 
     > Author Channel ID: UCeJ9LsUx9xeIKC6ibIxtOSQ
=============================================================================================


==================== Match Samples: One comment per matched-comment author ==================== 

1.  [x1]   UCd9J3_suj-_Wz_u2sk_aFIQ | Rossy- 🔥𝐆𝐨 𝐓𝐨 𝐌𝐲 ...: AJ deffo hitting that, no doubt                                                    
2.  [x1]   UCFoYBfA3egjy32tR2X-qqrA | SUSSY- 🔥𝐆𝐨 𝐓𝐨 𝐌𝐲 ...: AJ deffo hitting that, no doubt                                                    
3.  [x1]   UCFgY_1mol9enO4WfGk8SDuQ | Sussa-𝐹**СК МЕ - ...: Let’s go Shannon                                                                   
4.  [x1]   UCNH40MAvdPZDG9JR7zBcXpA | Zello-𝐹**СК МЕ - ...: Let’s go Shannon                                                                   
  

-------------------- Non-Matched Commenters, but who wrote many similar comments -------------------- 
---------------------- ( Similarity Threshold: 90%  |  Minimum Duplicates: 4 ) ---------------------- 

5.  [x24]  UCFwyIS84rpCdpGjLXbixpzQ | NaughtyDreamer ! ...: AJ deffo hitting that, no doubt                                                    
6.  [x23]  UCeJ9LsUx9xeIKC6ibIxtOSQ | ~NaughtyCuteness💋...: AJ got himself a real one
```

**Comment by DinhHuy2010** [comment] 2022-03-31 11:27
did you try the latest version?????

**Comment by GoukiMaster** [comment] 2022-03-31 19:57
Again, this was feedback for the beta. I didn’t have a problem since I use the latest stable, but I was giving feedback, as requested by the app program, when trying the beta.

 

At no point did I say “this isn’t working for me, please fix”. I clearly stated that the app asked to feedback this response, and I did.

**Comment by GoukiMaster** [comment] 2022-03-31 20:00
Okay, that’s my fault then. I used a beta I had saved without checking if there was a newer app version. I won’t bother with the feedback again.

**Comment by ThioJoe** [comment] 2022-03-31 20:00
Ok fair enough, but i would think it's kind of common sense to at least check if the issue is fixed in the latest version. Because if it is, then the feedback is not necessary

**Comment by GoukiMaster** [comment] 2022-03-31 20:32
I agree. Didn’t check though.

**Comment by Firecul** [comment] 2022-03-31 21:24
>  does the issue still occur in the latest version?

It didn't crash for me (using v2.16.6 .py) if that helps ThioJoe

**Comment by ThioJoe** [comment] 2022-04-02 03:05
Ok guess i'll just close this then

**Closed by ThioJoe** 2022-04-02 03:05 UTC
Labels: Bug / Error

**Comment by GoukiMaster** [comment] 2022-10-11 07:02
Just a side note… It was a while back I posted feedback, and I’m replying through email. What date did I submit feedback and what date was the beta reported on turned into stable?

**Comment by Firecul** [comment] 2022-10-11 10:12
You submitted feedback on the `2.15.0-Beta2` on 14th March, `2.15.0` was released to main on 7th Feburary.
