### ISSUE TITLE
[Bug]: Error - Code: X-2

### ISSUE THREAD

**Issue by MiLeX84** [ThioJoe/YT-Spammer-Purge#824] opened 2022-05-12 22:35 UTC
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Traceback (most recent call last):
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1674, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1651, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1208, in primaryInstance
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1191, in scan_video
  File "Scripts\operations.py", line 155, in get_comments
UnboundLocalError: local variable 'videoID' referenced before assignment
------------------------------------------------
Error Message: local variable 'videoID' referenced before assignment

Error - Code: X-2 occurred. This is almost definitely my fault and requires patching (big bruh moment)
Please post a bug report on the GitHub issues page, and include the above error info.
Short Link: TJoe.io/bug-report
    (In the mean time, try using a previous release of the program.)

### Release version

YTSpammerPurge.2.16.9

### Steps to reproduce

1. Scan recent videos for a channel
2. https://www.youtube.com/c/AidanMillward
3. Sensitive-Smart Mode
4. last 20 or 50 videos, happened every time

### What platform are you seeing this problem on?

Windows (.exe file)

**Comment by Firecul** [comment] 2022-05-13 02:25
Did you use `https://www.youtube.com/c/AidanMillward` or the channel ID URL `https://www.youtube.com/channel/UC6RKpfiMMylubgI6cAj2kNg`?

**Comment by ThioJoe** [comment] 2022-05-17 17:55
Hm odd, I can't reproduce it. Does it still happen now? I wonder if there was something about the videos at the time.

If it does still happen, on which video being scanned does it happen?

**Comment by killtheplanet** [comment] 2022-05-27 08:35
Not OP however this started happening to me on a Linux install as well with a particular video when doing a 'last 20' auto-smart scan. It is odd as the video is not the youngest so something probably changed over time.

Video [link](https://www.youtube.com/watch?v=VQRrjzoMzyo)

The same error occurs when doing a auto-smart on the specific video,

```
                          --- Scanning ---

Scanning 1/1: Bitcoin Mining Farms are DYING?! Luna & UST Crash Crypto SCAM

Traceback (most recent call last):
  File "./YTSpammerPurge.py", line 1674, in <module>
    main()
  File "./YTSpammerPurge.py", line 1651, in main
    continueRunning = primaryInstance(miscData)
  File "./YTSpammerPurge.py", line 1208, in primaryInstance
    status = scan_video(miscData, config, filtersDict, scanVideoID, videosToScan=videosToScan, currentVideoDict=currentVideoDict, videoTitle=videoTitle, showTitle=True, i=i)
  File "./YTSpammerPurge.py", line 1191, in scan_video
    nextPageToken, currentVideoDict = operations.get_comments(current, filtersDict, miscData, config, currentVideoDict, scanVideoID, nextPageToken, videosToScan=videosToScan)
  File "/home/killtheplanet/youtube-spammer-purge/Scripts/operations.py", line 155, in get_comments
    check_duplicates(current, config, miscData, allVideoCommentsDict, videoID)
UnboundLocalError: local variable 'videoID' referenced before assignment
------------------------------------------------
Error Message: local variable 'videoID' referenced before assignment

Error - Code: X-2 occurred. This is almost definitely my fault and requires patching (big bruh moment)
Please post a bug report on the GitHub issues page, and include the above error info.
Short Link: TJoe.io/bug-report
    (In the mean time, try using a previous release of the program.)
                                    
 Press Enter to Exit...          

```

Hope this helps!

**Comment by Firecul** [comment] 2022-05-27 15:42
> Not OP however this started happening to me on a Linux install as well with a particular video when doing a 'last 20' auto-smart scan. It is odd as the video is not the youngest so something probably changed over time.
> 
> Video [link](https://www.youtube.com/watch?v=VQRrjzoMzyo)
> 
> The same error occurs when doing a auto-smart on the specific video,
> 
> Hope this helps!

I get the same error on windows using .py also (I don't have the exe to try with atm.)

**Comment by ThioJoe** [comment] 2022-09-15 18:31
I still couldn't reproduce this, but I believe it is the same problem as #851, which should be fixed with https://github.com/ThioJoe/YT-Spammer-Purge/commit/44d693b544092893bfc850f6644e04ef4f097f96

**Closed by ThioJoe** 2022-09-15 18:31 UTC
Labels: Bug / Error, need-more-info
