### ISSUE TITLE
[Bug]: Output line spams text if string is longer than window width

### ISSUE THREAD

**Issue by Tomparkes93** [ThioJoe/YT-Spammer-Purge#951] opened 2022-10-17 18:11 UTC
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

When scanning comments across a channel, if the line that reads 
" Total: [19996/31098] (64%) | Comments Scanned: 15632 | Replies Scanned: 4364 | Matches Found So Far: 784" 
gets longer than the width of the window, it doesn't overwrite the line, but instead just adds it to the end and causes massive overflow & scrolling. 

If this is an issue with CMDPrompt then close this issue as unfixable or something. 

### Steps to reproduce

1. 
2. 
3. 

### What platform are you seeing this problem on?

Windows (.exe file)

### Screenshots

![example](https://user-images.githubusercontent.com/23336778/196251288-c8fb2edd-cf3a-4d7e-a4ba-b56a9b6f2a92.png)

**Comment by ThioJoe** [comment] 2022-10-17 19:18
Did you happen to resize the window while it was running? That is usually the cause of this

**Comment by ThioJoe** [comment] 2022-12-08 16:17
Closing assuming my above theory is correct

**Closed by ThioJoe** 2022-12-08 16:17 UTC
Labels: Bug / Error
