### ISSUE TITLE
Running into issues when logging in with my Google Cloud Application.

### ISSUE THREAD

**Issue by JohnMackYouTube05** [ThioJoe/YT-Spammer-Purge#245] opened 2021-12-28 15:30 UTC
When I run the Spammer Purge application for the first time, it tells me to log in. 
So I log in, it instantly closes the application after I press the Continue button on the OAuth Consent screen.

I figured your application was throwing an error I couldn't see, so I ran it from Command Prompt.
This time, after the application crashed, the following message printed to the console:
```
OPENSSL_Uplink(00007FFC4F5DCD30,08): no OPENSSL_Applink
```

I already have my client_secrets.json file in the same directory as the EXE, I made a whole other directory just for the EXE and its needed assets. Can someone help me here?

**Comment by KendallDoesCoding** [comment] 2021-12-28 18:23
> 

It shouldn't but maybe. Also, can you please share screenshots of the error. You're supposed to fill in the full bug report template. You should've reported this as a bug @JohnMackYouTube05 .

**Comment by KendallDoesCoding** [comment] 2021-12-28 18:25
I suggest you make a new issue under "Bug Report" fill in the template, so we can understand your issue better, add some screenshots in the description or in the thread comments, and close this here by saying "Closing in favour of #(new thread number)"

**Comment by KendallDoesCoding** [comment] 2021-12-28 18:29
> I suggest you make a new issue under "Bug Report" fill in the template, so we can understand your issue better, add some screenshots in the description or in the thread comments, and close this here by saying "Closing in favour of #(new thread number)"

URL: https://github.com/ThioJoe/YT-Spammer-Purge/issues/new?assignees=ThioJoe&labels=bug&template=bug_report.yaml&title=%5BBug%5D%3A+%28Enter+short%2C+one+sentence+summary+of+bug+here%29

**Comment by ThioJoe** [comment] 2021-12-28 18:57
Hm have you tried older releases of the program, and do they work? If so, could you see which one starts causing the problem?

**Comment by JohnMackYouTube05** [comment] 2021-12-28 18:58
I will try older releases. One minute

> Hm have you tried older releases of the program, and do they work? If so, could you see which one starts causing the problem?

**Comment by JohnMackYouTube05** [comment] 2021-12-28 19:01
Okay, so I've just tried Versions 2.3.0, and 2.2.5. Both of them produce the exact same error:
![image](https://user-images.githubusercontent.com/16242045/147598463-8f1c79c5-6e26-4ac0-a131-975be1dcad74.png)

**Comment by Kurdakov** [comment] 2021-12-28 19:20
I'm sorry, but did you try python version 
python YoutubeSpammerPurge.py or
python3 YoutubeSpammerPurge.py (if you have several pythons )
py -3 YoutubeSpammerPurge.py ?
the problem might be in pyinstaller or might be in python ( I also thought about firewall issue - had to allow python to connect to the net before it authenticated me on windows ( in your case you'd probably need to allow both python and exe ) - but I already forgot details (though it was exactly about ssl but not the same error ) and might not be the cause here )

**Comment by JohnMackYouTube05** [comment] 2021-12-28 19:20
Guess I'm gonna have to download the source code and compile it myself.

**Comment by JohnMackYouTube05** [comment] 2021-12-28 19:23
![image](https://user-images.githubusercontent.com/16242045/147600017-5b2d4309-409b-447c-a681-b21fac5f49cf.png)
Yep! This works. The problem must be in the EXE or something. Thank you.

**Comment by Kurdakov** [comment] 2021-12-28 19:25
it's likely pyinstaller uses different openssl library, than Windows 11 uses

**Comment by joaogelado** [comment] 2021-12-28 19:50
> it's likely pyinstaller uses different openssl library, than Windows 11 uses

Strange, I use Windows 11 and it work just fine

**Comment by kiatchun** [comment] 2021-12-29 02:18
> > it's likely pyinstaller uses different openssl library, than Windows 11 uses
> 
> Strange, I use Windows 11 and it work just fine

Samw

**Comment by ThioJoe** [comment] 2021-12-29 03:27
Perhaps later I could try packaging it while on a Windows 11 machine.
Also you can just run it if you download and install python, there's nothing to compile.

**Comment by KendallDoesCoding** [comment] 2021-12-29 06:32
> Perhaps later I could try packaging it while on a Windows 11 machine. Also you can just run it if you download and install python, there's nothing to compile.

Yeah, just run it via python if the .exe isnt working.

**Comment by TechStudent11** [comment] 2021-12-30 00:38
@JohnMackYouTube05 Try creating a different cloud project. I doubt that would do anything (because it's apparent that it's a problem with the EXE) but, it could work.

@ThioJoe I haven't tried compiling this program on Windows 11, but when I do compile my own projects, it just works. Running the Python file also works.

**Comment by rbeer** [comment] 2021-12-30 07:57
> it's likely pyinstaller uses different openssl library, than Windows 11 uses

Haven't dug any deeper, but this is an error when OpenSSL can't find some process:
https://github.com/openssl/openssl/blob/1fac27050176f7ed00da5649266024265678f70c/ms/uplink.c#L76-L80

@JohnMackYouTube05 
Try running your compiled version and the .exe right after. Does that change anything?

**Comment by KendallDoesCoding** [comment] 2022-01-01 15:09
@JohnMackYouTube05 It's been 2 days since any discussion in this issue thread, please give a update if the issue has been fixed.

**Comment by ThioJoe** [comment] 2022-01-02 20:40
Assuming it was resolved because inactive, but we can re-open it if necessary

**Closed by ThioJoe** 2022-01-02 20:40 UTC
Labels: OS-Issue
