### ISSUE TITLE
api-ms-win-core-path-l1-1-0.dll

### ISSUE THREAD

**Issue by SoNickRND** [ThioJoe/YT-Spammer-Purge#519] opened 2022-02-03 12:06 UTC
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to run latest (2.14.3) exe version but then it crashes with  

"Can't run program 'cause api-ms-win-core-path-l1-1-0.dll is missing"

(Запуск программы невозможен, так как на компьютере отсутствует api-ms-win-core-path-l1-1-0.dll. Попробуйте переустановить программу. )

I tried to get dll from some shady "dllwiki" sites, but no luck, not sure if that dll was real or correct one.
Just using python script now.

Maybe I missing some windows updates, not sure.

### Release version

YTSpammerPurge.2.14.3.exe

### Steps to reproduce

1.  Run EXE on my PC
2.  It crashes

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
---------------------------
YTSpammerPurge.2.14.3.exe - Системная ошибка
---------------------------
Запуск программы невозможен, так как на компьютере отсутствует api-ms-win-core-path-l1-1-0.dll. Попробуйте переустановить программу. 
---------------------------
ОК   
---------------------------
```

### Screenshots

![image](https://user-images.githubusercontent.com/125238/152339580-ed2c4aab-c3fa-4919-b8bf-002f889b5b46.png)

**Comment by KendallDoesCoding** [comment] 2022-02-03 12:09
@SoNickRND Please share a transalation of the error, I think its russian?

**Comment by KendallDoesCoding** [comment] 2022-02-03 12:11
As stated in #502:

> I updated to 3.8, now have to rename it back, restart, and check again. Maybe later, in my evening, 20-22 UTC+3

Yes, please try running the new version.

**Comment by SoNickRND** [comment] 2022-02-03 12:15
> @SoNickRND Please share a transalation of the error, I think its russian?

I don't know how would look exact same error message in English. I did some rough translation right in issue:
`"Can't run program 'cause api-ms-win-core-path-l1-1-0.dll is missing"`

**Comment by SoNickRND** [comment] 2022-02-03 12:17
> 

Well, this update of Python doesn't related to "missed dll for exe" issue, I suppose.

**Comment by KendallDoesCoding** [comment] 2022-02-03 12:17
> > @SoNickRND Please share a transalation of the error, I think its russian?
> 
> I don't know how would look exact same error message in English. I did some rough translation right in issue: `"Can't run program 'cause api-ms-win-core-path-l1-1-0.dll is missing"`

Thanks even with my transalation it says more or less the same thing, but the transalation I gave wont be the error message displayed if the computer was in English, yours seems to be more like it.

**Comment by SoNickRND** [comment] 2022-02-03 12:20
> > > @SoNickRND Please share a transalation of the error, I think its russian?
> > 
> > 
> > I don't know how would look exact same error message in English. I did some rough translation right in issue: `"Can't run program 'cause api-ms-win-core-path-l1-1-0.dll is missing"`
> 
> Thanks even with my transalation it says more or less the same thing, but the transalation I gave wont be the error message displayed if the computer was in English, yours seems to be more like it.

![image](https://user-images.githubusercontent.com/125238/152341541-43ac7969-1265-4d70-8c08-5cdaccd18bf9.png)
Just searched web for "win7 dll missing" images.

**Comment by KendallDoesCoding** [comment] 2022-02-03 12:23
> ### Duplicate Issues
> * [x]  There are **no existing posts relating to my problem**
> * [ ]  There are **existing posts relating to my problem, but the solution given, doesn't work for me.**
> 
> ### What happened?
> Well, I was trying to run latest (2.14.3) exe version but then it crashes with
> 
> "Can't run program 'cause api-ms-win-core-path-l1-1-0.dll is missing"
> 
> (Запуск программы невозможен, так как на компьютере отсутствует api-ms-win-core-path-l1-1-0.dll. Попробуйте переустановить программу. )
> 
> I tried to get dll from some shady "dllwiki" sites, but no luck, not sure if that dll was real or correct one. Just using python script now.
> 
> Maybe I missing some windows updates, not sure.
> 
> ### Release version
> YTSpammerPurge.2.14.3.exe
> 
> ### Steps to reproduce
> 1. Run EXE on my PC
> 2. It crashes
> 
> ### What platform are you seeing this problem on?
> Windows (.exe file)
> 
> ### Relevant log output
> ```shell
> ---------------------------
> YTSpammerPurge.2.14.3.exe - Системная ошибка
> ---------------------------
> Запуск программы невозможен, так как на компьютере отсутствует api-ms-win-core-path-l1-1-0.dll. Попробуйте переустановить программу. 
> ---------------------------
> ОК   
> ---------------------------
> ```
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/125238/152339580-ed2c4aab-c3fa-4919-b8bf-002f889b5b46.png)

@SoNickRND I see in the background Windows Powershell is opened, are you running the .exe file via powershell? Why not just double tab the exe and open it?

**Comment by KendallDoesCoding** [comment] 2022-02-03 12:23
> > 
> 
> Well, this update of Python doesn't related to "missed dll for exe" issue, I suppose.

Yeah, I thought you were downloading the latest release of this project

https://github.com/ThioJoe/YT-Spammer-Purge/releases/tag/v2.14.3

**Comment by Kurdakov** [comment] 2022-02-03 12:24
that is because you use Windows 7 and dll is only from Windows 8.
as Windows 7 is officially discontinued - for most users that should not be a problem.

**Comment by KendallDoesCoding** [comment] 2022-02-03 12:25
> 

Well that's annoying coz I believe most people still didnt upgrade from Windows 7 to Windows 8 and above, ig now is the time for you to upgrade @SoNickRND lol

**Comment by SoNickRND** [comment] 2022-02-03 12:51
> 

Maybe later, to Debian, when MS shutdown all those fancy automatic driver download infra. :D
Still, Python script is working on Win7 :)

**Comment by KendallDoesCoding** [comment] 2022-02-03 12:56
> > 
> 
> Maybe later, to Debian, when MS shutdown all those fancy automatic driver download infra. :D Still, Python script is working on Win7 :)

Yes, running the python script a option but your getting a error there too #502 and Debian doesnt seem to be working #491

**Comment by KendallDoesCoding** [comment] 2022-02-03 13:02
> that is because you use Windows 7 and dll is only from Windows 8. as Windows 7 is officially discontinued - for most users that should not be a problem.

Created a PR adding a disclaimer messege in README #521

**Comment by KendallDoesCoding** [comment] 2022-02-03 13:03
> > > 
> > 
> > 
> > Maybe later, to Debian, when MS shutdown all those fancy automatic driver download infra. :D Still, Python script is working on Win7 :)
> 
> Yes, running the python script a option but your getting a error there too #502 and Debian doesnt seem to be working #491

@SoNickRND But don't worry about it, I think ThioJoe will be able to fix #502

**Comment by ThioJoe** [comment] 2022-02-03 15:11
Can you see if running the python version works and maybe just use that?

I could at some point see if it's possible to include the dll inside the exe, but I'd have to make sure it has stayed the same all the way since windows 8

**Comment by KendallDoesCoding** [comment] 2022-02-03 15:14
> Can you see if running the python version works and maybe just use that?
> 
> I could at some point see if it's possible to include the dll inside the exe, but I'd have to make sure it has stayed the same all the way since windows 8

Your telling him to run the new python version? v3.10.0? or to run the python version of this project?

**Comment by SoNickRND** [comment] 2022-02-03 16:17
> > Can you see if running the python version works and maybe just use that?
> > 
> > I could at some point see if it's possible to include the dll inside the exe, but I'd have to make sure it has stayed the same all the way since windows 8
> 
> Your telling him to run the new python version? v3.10.0? or to run the python version of this project?

3.10 not working with win7 too. 3.8 does. Maybe 3.9

**Comment by KendallDoesCoding** [comment] 2022-02-03 16:35
> > > Can you see if running the python version works and maybe just use that?
> > > I could at some point see if it's possible to include the dll inside the exe, but I'd have to make sure it has stayed the same all the way since windows 8
> > 
> > 
> > Your telling him to run the new python version? v3.10.0? or to run the python version of this project?
> 
> 3.10 not working with win7 too. 3.8 does. Maybe 3.9

If it works, please close this and #502

**Comment by KendallDoesCoding** [comment] 2022-02-04 05:16
@SoNickRND Please try to run this and see if your issue gets fixed. https://support.microsoft.com/en-us/topic/update-for-universal-c-runtime-in-windows-c0514201-7fe6-95a3-b0a5-287930f3560c 

This will also help us in updating the messege in #521 if required. Thanks a ton!

**Comment by SoNickRND** [comment] 2022-02-19 22:13
> @SoNickRND Please try to run this and see if your issue gets fixed. https://support.microsoft.com/en-us/topic/update-for-universal-c-runtime-in-windows-c0514201-7fe6-95a3-b0a5-287930f3560c

I have this patch installed, tried with new purger 2.16.2, same error.

**Comment by ThioJoe** [comment] 2022-03-10 21:24
What's odd is on Windows 11 at least, I don't even seem to have that file at all anyway. If I can find an official copy of the file I could try making the exe with the file included

**Comment by fluentmoheshwar** [comment] 2022-07-10 14:55
> What's odd is on Windows 11 at least, I don't even seem to have that file at all anyway. If I can find an official copy of the file I could try making the exe with the file included

I will try to fix it.

**Comment by fluentmoheshwar** [comment] 2022-07-10 15:16
> What's odd is on Windows 11 at least, I don't even seem to have that file at all anyway. If I can find an official copy of the file I could try making the exe with the file included

Managed to work in python. But when I convert it to exe. It refuse to work.

**Comment by fluentmoheshwar** [comment] 2022-07-10 15:18
The problem is the current version of python isn't compatible with windows 7.

**Comment by ThioJoe** [comment] 2023-03-09 22:02
Yea probably not much I can do for this

**Closed by ThioJoe** 2023-03-09 22:02 UTC
Labels: OS / Environment Issue
