### ISSUE TITLE
Nonetype not iterable

### ISSUE THREAD

**Issue by Arthyfloss** [ThioJoe/YT-Spammer-Purge#551] opened 2022-02-04 17:01 UTC
### Filter Mode

Auto-Smart Mode

### Select the Problem

Other (add details below)

### (Optional) If 'Other', Enter Very Short Description

Error at the end of the scan

### Spammer Example / Sample

It shows this :

TypeError: 'NoneType' object is not iterable
------------------------------------------------
Unknown Error - Code: X-5 occurred.

**Comment by KendallDoesCoding** [comment] 2022-02-04 18:55
> ### Filter Mode
> Auto-Smart Mode
> 
> ### Select the Problem
> Other (add details below)
> 
> ### (Optional) If 'Other', Enter Very Short Description
> Error at the end of the scan
> 
> ### Spammer Example / Sample
> It shows this :
> 
> ## TypeError: 'NoneType' object is not iterable
> Unknown Error - Code: X-5 occurred.
> 
> ### Video / Post Link
> _No response_
> 
> ### (Optional) Additional Info / Context
> _No response_

Firstly, this is not a filtering issue, you created a wrong issue thread. Secondly, it's ok but please share log input of the error or we wont be able to help you.

**Comment by djsv23** [comment] 2022-02-04 21:54
I can't tell without the actual log, but this looks like it's potentially a duplicate of #544

**Comment by ThioJoe** [comment] 2022-02-04 23:18
Yea I definitely believe it's a dupe of 544, so I'll close it here. Also it's fixed for the next release

**Closed by ThioJoe** 2022-02-04 23:18 UTC
Labels: bug
