### ISSUE TITLE
[Bug]: (Can't use "Scan recent videos for a channel" when using a config file)

### ISSUE THREAD

**Issue by BFG-BFG** [ThioJoe/YT-Spammer-Purge#236] opened 2021-12-27 17:48 UTC
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to use "Scan recent videos for a channel" with a brand new config file but then it gave me the error.

https://user-images.githubusercontent.com/77847519/147494204-4e049a7e-86f4-4a27-847d-2a9096cdc723.mp4

 

### Release version

v2.2.6

### Steps to reproduce

1. make a new config file
2.  use the config file
3.  do a ""Scan recent videos for a channel"
https://user-images.githubusercontent.com/77847519/147494204-4e049a7e-86f4-4a27-847d-2a9096cdc723.mp4

### What platform are you seeing this problem on?

Windows

### Relevant log output

```shell
File "C:\Joe\Documents\GitHub\YouTube-Spammer-purge\YouTubeSpammerPurge.py", line 2776, in <module>
File "C:\Joe\Documents\GitHub\YouTube-Spammer-purge\YouTubeSpammerPurge.py", line 2200, in main
Keyerror: 'channel to scan'
```

**Comment by ThioJoe** [comment] 2021-12-27 18:52
Ah crap you're right, I know what the problem is, the v2.2.6 exe was package with an old version of the default config. I'll upload a fix soon.

Duplicate of #224 issue

**Closed by ThioJoe** 2021-12-27 18:52 UTC
Labels: bug
